name: Tenderly deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'defi-wonderland/monitor-boilerplate'
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Install Tenderly Cli
        run: yarn tenderly-cli-install

      - name: npm install
        run: npm install

      - name: Deploy
        shell: bash
        env:
          TENDERLY_ACCESS_TOKEN: ${{ secrets.TENDERLY_ACCESS_TOKEN }}
          TENDERLY_USERNAME: ${{ secrets.TENDERLY_USERNAME }}
          TENDERLY_SLUG: ${{ secrets.TENDERLY_SLUG }}
        run: yarn deploy --debug
